### ISSUE TITLE
NPE on model verification

### ISSUE THREAD

**Issue by vdubikhin** [MyersResearchGroup/LEMA#66]
[C_element_new_approach.zip](https://github.com/MyersResearchGroup/LEMA/files/1939285/C_element_new_approach.zip)

Verifying model full.xml with Zone(Java) causes null pointer exception:
-------- Reachability Analysis ---------
---> calling function search_dfs
java.lang.NullPointerException
	at edu.utah.ece.async.lema.verification.timed_state_exploration.zoneProject.Zone.copyTransitions(Zone.java:3602)
	at edu.utah.ece.async.lema.verification.timed_state_exploration.zoneProject.Zone.addTransition(Zone.java:6399)
	at edu.utah.ece.async.lema.verification.timed_state_exploration.zoneProject.Zone.addTransition(Zone.java:87)
	at edu.utah.ece.async.lema.verification.platu.stategraph.StateGraph.fire(StateGraph.java:1570)
	at edu.utah.ece.async.lema.verification.platu.logicAnalysis.Analysis.search_dfs(Analysis.java:410)
	at edu.utah.ece.async.lema.verification.platu.project.Project.search(Project.java:272)
	at edu.utah.ece.async.ibiosim.gui.verificationView.VerificationView.run(VerificationView.java:1895)
	at java.lang.Thread.run(Unknown Source)

**Comment by cjmyers** [comment]
I think this is caused by having no delays on some of your transitions.  Can you try adding delays to all your transitions (0 is fine), then try again?
